### PR TITLE
Add post-id-xx or page-id-xx class to TinyMCE previews

### PR DESCRIPTION
**Pull request by BraadMartin**
This allows us to take advantage of any page or post-specific styling that we've got in the main stylesheet. It won't happen 100% automatically because none of the wrapper classes like .entry-content are used in the TinyMCE preview, but we can still get the styling into the preview by writing CSS rules like this:

.page-id-33 .entry-content h2,
.mce-content-body.page-id-33 h2 {
    color: red;
}

### CODE REVIEW

**Comment by MickeyKay** [comment]
Good concept - hold off on 2.1.0 release and add to next release per notes below. . .

This seems to work great for standard editing, but doesn't add the body class to TinyMCE when using the customizer (e.g. editing a Black Studio TinyMCE widget).

Check if there's a good way to add this functionality, and also check WP Core code to see how the standard post/page-id-XXXX is being added.

**Comment by MickeyKay** [comment]
@Braad - where does this one stand? I thought there was some additional work that needed to be done - is that the case?

One questions I have regarding this conditional test:
```
$screen = get_current_screen();
// If we're on an edit screen, add an appropriate 'post-id-XX' or 'page-id-XX'.
if ( 'edit' == $screen->parent_base ) {
...
```
What about front-end page builders, the customizer, etc? Seems like it might not work in these situations, however I haven't fully tested. Can you confirm that it works across the board? Is there a reason we need that conditional at all?

**Comment by BraadMartin** [comment]
This still needs to be modified to work in situations outside of the page edit screen. The original logic behind the conditional was that I didn't want to add a class like "-id-" to arbitrary TinyMCE instances that aren't tied to a page or post, but maybe this isn't such a big deal. There are always going to be cases where TinyMCE is used in things like widgets or a plugin's settings page that aren't tied to a page or post.

Maybe we can rely on whether the global $post object is there, but in the case of the Customizer I need to do more testing to see what context the $post object has when editing a widget. I'll work on this as time allows and hopefully work out a better solution. For now we could merge and continue to iterate if we wanted to, as the current solution works great but is just limited to post/page edit screens. I'm fine waiting for the optimal solution also.

**Comment by MickeyKay** [comment]
Gotcha. Okay, I'm going to change the milestone on this one then.

**Comment by MickeyKay** [comment]
Decided we're just going to drop it in as is. One point that came up in discussion is that it can be risky to style things based on page/post-specific ID's, because the client can always copy and paste content into a new page. Doesn't hurt anything though, and may prove useful.

**Pull request merged**
