### PR TITLE
Fix/beaver builder

### LINKED ISSUE #44: Page Builder Problems
This is probably an edge case and I apologise for wasting your time but I like to use Trestle and Beaver Builder together.
Unfortunately I just discovered BB doesn't work with the most recent version of Trestle. If I revert to my previous copy of 1.0.0 everything works ok again.
I have examined the latest version of Trestle as best I can to try and work out what might be causing a conflict but no luck so far. It's odd because BB seems to work with other Genesis themes. 
When there is a problem it is usually to do with a script conflict.
Can you think off the top of your head what might have changed in the last couple of commits to make BB stop working?

### PR DESCRIPTION
**Pull request by MickeyKay**
Fixes #44 

Previously, the trestle_tiny_mce_before_init filter was causing a fatal
error when it was trying to call get_current_screen() on the front-end,
which isn't availably unless /wp-admin/includes/screen.php is included,
which it isn't on the front end. This patch switches from checking the
current screen to simply checking if the post object exists. Not sure if
there are any edge cases where the current screen check does something
the post check doesn't - I'll leave that to you @braad to decide as I
think you added this code.

### CODE REVIEW

**Comment by MickeyKay** [comment]
Have a looksy @BraadMartin

**Comment by BraadMartin** [comment]
As a quick fix it looks fine. The goal of the function in question was to add a page-id-XX or post-id-XX class to the TinyMCE body so that any post specific styling included on such a class would come through in the editor, but it's definitely a nice to have rather than a must have, and I think with this fix it will still work in the main context of a post/page edit screen.

**Comment by MickeyKay** [comment]
Cool - you want to bump the version and tag this one (and possibly let Neil know)?

**Comment by BraadMartin** [comment]
I'm happy to let Neil know. We should probably bump the version but I'm a bit busy today, and it is pretty minor. If you want to tag a new version feel free, otherwise I'll keep it on my list and do it asap. We've got some other changes that are pretty much ready to go and would be good to include in the next release, like removing the favicon option (now that the Site Icons feature is in Core), so maybe I'll try to get those included, but feel free to tag a new release if you've got the time and desire.

**Comment by MickeyKay** [comment]
Cool, will do right now.
ᐧ

**Comment by MickeyKay** [comment]
And. . . done.
ᐧ

**Pull request merged**
